<a href="https://colab.research.google.com/github/sergekamanzi/Fraudent-Docs/blob/main/transaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [10]:
data = pd.read_csv('/content/fraud detection.csv')
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,380.0,CASH_OUT,92888.94,C2054348498,27657.00,0.00,C1853199806,5838781.76,5931670.70,0.0,0.0
1,646.0,TRANSFER,399045.08,C724693370,10399045.08,10399045.08,C1909486199,0.00,0.00,1.0,1.0
2,384.0,CASH_IN,35416.73,C1095508813,1154711.52,1190128.25,C961243143,927932.70,892515.97,0.0,0.0
3,518.0,CASH_IN,52211.31,C1867780533,2985.00,55196.31,C1425168473,433652.93,381441.62,0.0,0.0
4,450.0,CASH_OUT,1463764.35,C2142422300,1463764.35,0.00,C1173885211,385211.95,1848976.30,1.0,0.0

In [11]:
data.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,7050.000000,7.050000e+03,7.050000e+03,7.050000e+03,7.050000e+03,7.050000e+03,7050.000000,7050.000000
mean,285.255177,5.425332e+05,1.018520e+06,6.381589e+05,9.555733e+05,1.273450e+06,0.290780,0.000567
std,174.266294,1.533102e+06,3.013717e+06,2.684439e+06,4.286751e+06,4.897417e+06,0.454154,0.023815
min,6.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,163.000000,2.188457e+04,1.712300e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
50%,265.000000,1.265790e+05,4.957450e+04,0.000000e+00,2.623340e+03,1.586073e+05,0.000000,0.000000
75%,379.000000,3.291337e+05,4.133118e+05,3.295994e+04,6.995410e+05,1.077128e+06,1.000000,0.000000
max,743.000000,2.515081e+07,4.489219e+07,3.489219e+07,2.772997e+08,2.916677e+08,1.000000,1.000000

In [12]:
data.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [13]:
data = data.drop(columns=["nameOrig", "nameDest"])
data.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,380.0,CASH_OUT,92888.94,27657.00,0.00,5838781.76,5931670.70,0.0,0.0
1,646.0,TRANSFER,399045.08,10399045.08,10399045.08,0.00,0.00,1.0,1.0
2,384.0,CASH_IN,35416.73,1154711.52,1190128.25,927932.70,892515.97,0.0,0.0
3,518.0,CASH_IN,52211.31,2985.00,55196.31,433652.93,381441.62,0.0,0.0
4,450.0,CASH_OUT,1463764.35,1463764.35,0.00,385211.95,1848976.30,1.0,0.0

In [15]:
# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to the 'type' column
data['type'] = le.fit_transform(data['type'])
data.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,380.0,1,92888.94,27657.00,0.00,5838781.76,5931670.70,0.0,0.0
1,646.0,4,399045.08,10399045.08,10399045.08,0.00,0.00,1.0,1.0
2,384.0,0,35416.73,1154711.52,1190128.25,927932.70,892515.97,0.0,0.0
3,518.0,0,52211.31,2985.00,55196.31,433652.93,381441.62,0.0,0.0
4,450.0,1,1463764.35,1463764.35,0.00,385211.95,1848976.30,1.0,0.0

In [16]:
data.shape

(7050, 9)

In [19]:
# Initialize the StandardScaler
scaler = StandardScaler()

# List of numeric columns to scale (excluding target variables like isFraud)
numeric_cols = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

# Apply the scaler to the numeric columns
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

In [22]:
# Split features and target labels
X = data.drop(columns=['isFraud', 'isFlaggedFraud'])
Y = data[['isFraud', 'isFlaggedFraud']]